name: Android CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm64"]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      MY_API_TOKEN: ${{ secrets.MY_API_TOKEN }}
      MY_PRIVATE_API_TOKEN: ${{ secrets.MY_PRIVATE_API_TOKEN }}

    steps:
      - name: Set IS_MAIN_BRANCH if on main branch
        if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'main'
        run: echo "IS_MAIN_BRANCH=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@main

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@master
        with:
          workflow: main.yml
          path: app_pojav_zh/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: main
          name: lwjgl

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@main

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Debug ${{matrix.arch}}
        run: |
          chmod +x gradlew
          ./gradlew app_pojav_zh:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Debug ${{matrix.arch}}
        uses: actions/upload-artifact@v4
        with:
          name: PZH-X-PGW(Debug)-${{matrix.arch}}
          path: app_pojav_zh/build/outputs/apk/debug/*
